<?php
echo $this->headLink()
        ->prependStylesheet($this->basePath('customer/sidebar/css/custom.css'))
?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath('customer/sidebar/js/custom.js'))
;
?>
<div>
    <div class="panel theme-panel">
        <div class="panel-heading">
            <span class="panel-title">

            </span>
        </div>
        <div class="panel-body">
            <div class="col-lg-12">
                <div class="col-md-2 col-md-offset-1  thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (3).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1 thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (2).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1  thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (3).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1 thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (2).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="col-md-2 col-md-offset-1  thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (3).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1 thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (2).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1  thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (3).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1 thumbnail">
                    <div class="feature-box">
                        <img class="col-lg-12" src="<?php echo $this->basePath('img/icons/config (2).png'); ?>" alt=""
                             />
                        <div class="col-lg-12">One code used for all device</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

