<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<meta charset="UTF-8">
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo/marie.png'))
        ->prependStylesheet($this->basePath('customer/date/css/style.css'))
        ->prependStylesheet($this->basePath('customer/date/css/bootstrap-select'))
        ->prependStylesheet($this->basePath('customer/date/css/bootstrap-select.min.css'))
        ->prependStylesheet($this->basePath('customer/date/css/jquery.datetimepicker.css'))
        ->prependStylesheet('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.full.min.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.full.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.min.js'))
        ->prependFile($this->basePath('customer/date/js/bootstrap-select.js'))
;
?>
<div>
    <div>
        <form class="form-horizontal col-lg-12" method="POST" enctype="multipart/form-data" style="border: 2px solid #CBE6F4;background-color: white">
            <br/>
            <div class="form-group">
                <label for="nom" class="col-sm-3 control-label">Nom et Prenom:</label>
                <div class="col-sm-8">
                    <input type="text" name="nom" class="form-control" id="nom" title="nom" placeholder="nom" required="false">
                </div>
            </div>
            <div class="form-group">
                <label for="enVie" class="col-sm-3 control-label">Genre</label>
                <div class="col-sm-8 radio">
                    <label><input type="radio" name="type" value="frere" class="active">frere</label>
                    <label><input type="radio" name="type" value="soeur">soeur</label>
                </div>
            </div>
            <div class="form-group">
                <label for="idPersonnel" class="col-sm-3 control-label">De:</label>
                <div class="col-sm-5">
                    <select class="form-control col-sm-8" id="idPersonnel" name="idPersonnel" title="idPersonnel" required="true">
                        <option value="" style="color: deepskyblue">-- Sélectionner le concerné --</option>
                        <?php
                        foreach ($personnels as $personne) {
                            echo '<option value="' . $personne->getIdPersonnel() . '" style="color: deepskyblue"> &nbsp;' . $personne->getNom() . '   ' . $personne->getPrenom() . ' </option>';
                        }
                        ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="type" class="col-sm-3 control-label">Ordre Familial:</label>
                <div class="col-sm-8">
                    <select class="form-control col-sm-8" id="ordreFamilial" name="ordreFamilial" title="ordreFamilial" required="true">
                        <option value="" style="color: deepskyblue">-- Sélectionner l'ordre --</option>
                        <option value="1" style="color: deepskyblue">&nbsp;&nbsp; numero 1</option>
                        <option value="2" style="color: deepskyblue">&nbsp;&nbsp; numero 2</option>
                        <option value="3" style="color: deepskyblue">&nbsp;&nbsp; numero 3</option>
                        <option value="4" style="color: deepskyblue">&nbsp;&nbsp; numero 4</option>
                        <option value="5" style="color: deepskyblue">&nbsp;&nbsp; numero 5</option>
                        <option value="6" style="color: deepskyblue">&nbsp;&nbsp; numero 6</option>
                        <option value="7" style="color: deepskyblue">&nbsp;&nbsp; numero 7</option>
                        <option value="8" style="color: deepskyblue">&nbsp;&nbsp; numero 8</option>
                        <option value="9" style="color: deepskyblue">&nbsp;&nbsp; numero 9</option>
                        <option value="10" style="color: deepskyblue">&nbsp;&nbsp; numero 10</option>

                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="etatPsychologique" class="col-sm-3 control-label">Etat Psychologique :</label>
                <div class="col-sm-8">
                    <input type="text" name="etatPsychologique" class="form-control" id="etatPsychologique" title="etatPsychologique" placeholder="etatPsychologique" required="false">
                </div>
            </div>
            <div class="form-group">
                <label for="enVie" class="col-sm-3 control-label">Est en vie ? :</label>
                <div class="col-sm-8 radio">
                    <label><input type="radio" name="enVie" value="oui" class="active">Oui</label>
                    <label><input type="radio" name="enVie" value="non" class="active" >Non</label>
                </div>
            </div>

            <div class="row col-sm-offset-2">
                <div class="col-sm-2">
                    <button type="submit" name="submit" class="btn btn-default ">Enregistrer</button>
                    <br>
                    <br>
                </div>
                <div class="col-sm-2" style="margin-left: 20px">
                    <button type="cancel" name="cancel" class="btn btn-default " >Annuler</button>
                    <br>
                    <br>
                </div>
            </div>

        </form>
    </div>
</div>
