<div>
    <?php
   foreach ($fraternites as $frere) {

        echo '<label> Nom  : </label>&nbsp;' . $frere->getNom(). '<br>';
        echo '<label> Type: </label>&nbsp;' . $frere->getType() . '<br>';
        echo '<label> Ordre Familial </label>&nbsp;' . $frere->getOrdreFamilial(). '&nbsp;&nbsp;&nbsp;';
        echo '<label> Est En Vie? </label>&nbsp;' . $frere->getEnVie();
        echo '<article>
        <div class="bottom-article">';






        echo '<ul class="meta-post">
                <li><i class="icon-calendar"></i><a href="#" data-toggle="modal" data-target="#myModal"> Details</a></li>
                <li><i class="icon-user"></i><a href="#"> Anniversaire</a></li>
                <li><i class="icon-folder-open"></i><a href="#"> SMS</a></li>
                <li><i class="icon-comments"></i><a href="#">Commentaires</a></li>
            </ul>
        </div>
    </article>';
        
        echo '<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">';
        echo '<div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Amadou Bakari</h4>
            </div>
            <div class="modal-body">
                <iframe src="' . $this->basePath('documents/photos/' . $personnel['photo']) . '" width="500"
                        height="500"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="">Download</button>
            </div>
        </div>
</div>';
    }
    ?>
</div>





























<nav>
    <ul class="pagination pagination-sm">
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>





























<nav>
    <ul class="pagination pagination-sm">
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

