<?php
echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CICM-ACO' . $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('img/logo/logocicmaoc.png')))
                ->prependStylesheet($this->basePath('bootstrap/css/style.css'))
                ->prependStylesheet($this->basePath('bootstrap/css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('bootstrap/css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/customer.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('bootstrap/js/bootstrap.min.js'))
                ->prependFile($this->basePath('bootstrap/js/jquery.min.js'))
                ->prependFile($this->basePath('bootstrap/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('bootstrap/js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->render('layout/header.phtml'); ?>
        </div>
        <div class="container">
            <div class="col-lg-8" style="margin-left: 0" >
                <?php echo $this->content; ?>
            </div> <div class="col-lg-4" style="background-color: white">
                <?php echo $this->render('layout/right.phtml'); ?>
            </div>
        </div>
        <hr class="container">
        <div class="container">
            <?php echo $this->render('layout/footer.phtml'); ?>
            <hr>
            <footer class="container">
                <p style="color: black">&copy; <?php echo date('Y') ?> by CICM-ACO <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
