<div>
    <?php
    foreach ($documents as $doc) {

        echo '<div style="background-color: white; padding-left: 5px; padding-top: 10px; margin-top: 2px; padding-right: 5px">';
        echo '<div class="row">';
        echo '<div class = "col-lg-2">';
        echo '<img src = "' . $this->basePath('documents/officiels/' . $doc->getFichier()) . '" class = "img-thumbnail" style = "width: 100px;height: 100px" alt = "Cinque Terre"></div>';
        echo '<div class = "col-lg-10">';
        echo '<label>Type :</label>&nbsp;' . $doc->getType() . '<br>';
        echo '<label>Proprietaire : </label>&nbsp;' . $doc->getIdPersonnel()->getNom() . '<br>';
        echo '<article>
        <div class="bottom-article">';

        echo '<ul class="meta-post">
                <li><i class="icon-calendar"></i><a href="#" data-toggle="modal" data-target="#' . $doc->getIdPersonnel()->getNom() . '"> Details</a></li>
                <li><i class="icon-user"></i><a href="#"> Modifier</a></li>
                <li><i class="icon-folder-open"></i><a href="#"> Supprimer</a></li>
                <li><i class="icon-comments"></i><a href="' . $this->basePath('documents/officiels/' . $doc->getFichier()) . '">Télécharger</a></li>
            </ul>
        </div>
    </article>
</div></div></div>';




        echo '<div class="modal fade" id="' . $doc->getIdPersonnel()->getNom() . '" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">';
        echo '<div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">' . $doc->getDescription() . '</h4>
            </div>
            <div class="modal-body">
                <iframe src="' . $this->basePath('documents/officiels/' . $doc->getFichier()) . '" width="500"
                        height="500"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="">Download</button>
            </div>
        </div>
    </div>
</div>';
    }
    ?>
</div>


<div id="pagination">
    <?php
    echo $this->paginationControl($documents, 'Sliding', // All, Elastic, Jumping, Sliding
            'search_pagination.phtml', array('route' => 'document/paginator-doctrine'));
    ?>
    <!-- 'search_pagination.phtml' 'item_pagination.phtml' dropdown_pagination.phtml -->
    <!-- ToDo, 'controller' => 'user-doctrine-paginator', array('controler'=>'user-doctrine-paginaytor') -->
</div>