<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <div>
            <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Sexe</th>
                        <th>Email</th>
                        <th>Etablissement</th>
                        <th>Date d'abonnement</th>
                        <th>Date d'expiration</th>
                        <th>Statut</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Sexe</th>
                        <th>Email</th>
                        <th>Etablissement</th>
                        <th>Date d'abonnement</th>
                        <th>Date d'expiration</th>
                        <th>Statut</th>                    
                    </tr>
                </tfoot>
                <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><a href="#">Modifier</a>&nbsp;|&nbsp;<a href="#">Supprimer</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>
