<meta charset="UTF-8">
<?php
//session_start();
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo/marie.png'))
        ->prependStylesheet($this->basePath('customer/date/css/style.css'))
        ->prependStylesheet($this->basePath('customer/bootstrap-form-helper/css/bootstrap-formhelpers.min.css'))
        ->prependStylesheet($this->basePath('customer/bootstrap-form-helper/css/bootstrap-formhelpers.css'))
        ->prependStylesheet($this->basePath('customer/date/css/jquery.datetimepicker.css'))
        ->prependStylesheet('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css')
?>

<!-- Scripts -->
<?php
echo $this->headScript()
        ->prependFile($this->basePath('customer/bootstrap-form-helper/js/bootstrap-formhelpers.min.js'))
        ->prependFile($this->basePath('customer/bootstrap-form-helper/js/bootstrap-formhelpers.js'))
        ->prependFile($this->basePath('customer/bootstrap-form-helper/js/bootstrap-formhelpers-selectbox.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.js'))
        ->prependFile($this->basePath('customer/date/js/jquery.datetimepicker.min.js'))
        ->prependFile($this->basePath('customer/date/js/bootstrap-select.js'))
;
?>
<div class="text-center" style="display: block">
    <div class="arrow">
        <?php
//        $compte = $_SESSION['connected'];
//        echo $compte;
        ?>
    </div>
    <div style="background-color: white">
        <img class="col-xs-12" src="<?php echo $this->basePath('img/logo/marie.png'); ?>" />
    </div>
</div>
