<div>
    <?php
    foreach ($personnels as $personnel) {

        echo '<div style="background-color: white; padding-left: 5px; padding-top: 10px; margin-top: 2px; padding-right: 5px">';
        echo '<div class="row">';
        echo '<div class = "col-lg-2">';
        echo '<img src = "' . $this->basePath('documents/photos/' . $personnel->getPhoto()) . '" class = "img-thumbnail" style = "width: 100px;height: 100px" alt = "Cinque Terre"></div>';
        echo '<div class = "col-lg-7">';
        echo '<label>Nom :</label>&nbsp;' . $personnel->getNom() . '<br>';

        echo '<label>Prénom : </label>&nbsp;' . $personnel->getPrenom() . '<br>';
        echo '<label>Statut :</label>&nbsp;' . $personnel->getTypePersonnel() . '  [' . $personnel->getIdService() . '  ' . $personnel->getEcole() . '  ' . $personnel->getFiliere() . ']<br>';
        echo '<label>Domicilié à : </label>&nbsp;' . $personnel->getDomicile() . '<br></div></div>';
        echo ' <br>';
        echo '<article>
        <div class="post-quote">
            <blockquote>
                <i class="icon-quote-left"></i>' . $personnel->getNom() . '  ' . $personnel->getPrenom() . '  Née le ' . $personnel->getDateDeNaissance()->format('d-m-Y') . '
              à ' . $personnel->getLieuDeNaissance() . ' et domicilié à ' . $personnel->getDomicile() . ' .Fils de ' . $personnel->getNomPere() . ' et de ' . $personnel->getNomMere() . '      



            </blockquote>
        </div>
        <div class="bottom-article">';
        echo '<ul class="meta-post">
                <li><i class="icon-calendar"></i><a href="#" data-toggle="modal" data-target="#' . $personnel->getNom() . '"> Details</a></li>';


        if (isset($_SESSION['connected']) == TRUE) {
            if ($_SESSION['profil'] == "ADMIN") {
                echo '<li><i class="glyphicon glyphicon-pencil"></i><a href="' . $this->url('personnel/default', array('controller' => 'personnel', 'action' => 'editpretre', 'id' => $personnel->getIdPersonnel())) . '">Modifier</a></li>
                <li><i class="glyphicon glyphicon-trash"></i><a data-toggle="modal" data-target="#' . $personnel->getNom() . '2" href="#">Supprimer</a></li> 
                <li><i class="glyphicon glyphicon-download-alt"></i><a href="' . $this->url('personnel/default', array('controller' => 'export', 'action' => 'exportpdf', 'id' => $personnel->getIdPersonnel())) . '">Télécharger CV</a></li>
                <li><i class="glyphicon glyphicon-paperclip"></i><a href="' . $this->url('document/default', array('controller' => 'document', 'action' => 'add', 'id' => $personnel->getIdPersonnel())) . '"> Joindre Documents</a></li>
                <li><i class="glyphicon glyphicon-book"></i><a href="' . $this->url('document/default', array('controller' => 'document', 'action' => 'index', 'id' => $personnel->getIdPersonnel())) . '"> Lister documents</a></li>
                ';
            } elseif ($_SESSION['personnel']->getIdPersonnel() == $personnel->getIdPersonnel()) {
                echo '<li><i class="glyphicon glyphicon-pencil"></i><a href="' . $this->url('personnel/default', array('controller' => 'personnel', 'action' => 'editpretre', 'id' => $personnel->getIdPersonnel())) . '">Modifier</a></li>
                <li><i class="glyphicon glyphicon-download-alt"></i><a href="' . $this->url('personnel/default', array('controller' => 'export', 'action' => 'exportpdf', 'id' => $personnel->getIdPersonnel())) . '">Télécharger CV</a></li>                   
            ';
            }
        }
        echo ' </ul>
        </div>
    </article>
</div>
        <div class="modal fade" id="' . $personnel->getNom() . '" tabindex="-1" role="dialog" aria-labelledby="' . $personnel->getNom() . 'Label">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="' . $personnel->getNom() . 'Label">' . $personnel->getNom() . ' ' . $personnel->getPrenom() . '</h4>
            </div>
            <div class="modal-body">
                <iframe src="' . $this->basePath('documents/photos/' . $personnel->getPhoto()) . '" width="450"
                        height="250"></iframe><br>
                <label>Nom :</label>&nbsp;' . $personnel->getNom() . '<br>
                <label>Prénom : </label>&nbsp;' . $personnel->getPrenom() . '<br>
                <label>Statut :</label>&nbsp;' . $personnel->getTypePersonnel() . '  [' . $personnel->getIdService() . '  ' . $personnel->getEcole() . '  ' . $personnel->getFiliere() . ']<br>
                <label>Date de naissance :</label>&nbsp;' . $personnel->getDateDeNaissance()->format('d-m-Y') . '<br>
                <label>Lieu de naissance :</label>&nbsp;' . $personnel->getLieuDeNaissance() . '<br>
                <label>Domicilié à :</label>&nbsp;' . $personnel->getDomicile() . '<br>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>';
        if (isset($_SESSION['connected']) == TRUE) {
            if ($_SESSION['profil'] == "ADMIN") {
                echo '<a class="btn btn-primary" href="' . $this->url('personnel/default', array('controller' => 'export', 'action' => 'exportpdf', 'id' => $personnel->getIdPersonnel())) . '">Télécharger CV</a>';
            } elseif ($_SESSION['personnel']->getIdPersonnel() == $personnel->getIdPersonnel()) {
                echo '<a class="btn btn-primary" href="' . $this->url('personnel/default', array('controller' => 'export', 'action' => 'exportpdf', 'id' => $personnel->getIdPersonnel())) . '">Télécharger CV</a>';
            }
        }


        echo '                      
            </div>
            </div>
            </div>
            </div>';
        echo '<!-- Modal -->
                            <div class="modal fade" id="' . $personnel->getNom() . '2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Suppression</h4>
                                  </div>
                                  <div class="modal-body">
                                  voulez vous supprimer ' . $personnel->getNom() . '  ' . $personnel->getPrenom() . '
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-warning" data-dismiss="modal">Annuler</button>
                                    <a href="' . $this->url('personnel/default', array('controller' => 'personnel', 'action' => 'delete', 'id' => $personnel->getIdPersonnel())) . '" type="button" class="btn btn-primary">Supprimer</a>
                                  </div>
                                </div>
                              </div>
                            </div>';
    }
    ?>
</div>
<div>

    <?php
    echo $this->paginationControl($this->personnels, 'Jumping', // All, Elastic, Jumping, Sliding
            'search_pagination.phtml', array('route' => 'personnel/paginator-doctrine'));
    ?>
    <!-- 'search_pagination.phtml' 'item_pagination.phtml' dropdown_pagination.phtml -->
    <!-- ToDo, 'controller' => 'user-doctrine-paginator', array('controler'=>'user-doctrine-paginaytor') -->
</div>
